### ISSUE TITLE
No health endpoint

### ISSUE THREAD

**Issue by renjithkr-dev** [udacity/nd9990-c3-microservices-exercises#21]
Readme mentions about the health endpoint, but none defined in nd9990-c3-microservices-exercises/lesson-5-kubernetes-for-production/exercises/debugging-logs/server.js

**Comment by SudKul** [comment]
Hi @renjithkr-dev 
Apologies for an extremely delayed response. 
We are cleaning up the Udacity repos. 
I can see an endpoint [here](https://github.com/udacity/nd9990-c3-microservices-exercises/blob/cad6ddcbdcc87a3d7bd9dee5f1a5a61d3733af99/lesson-5-kubernetes-for-production/exercises/simple-express/server.js#L8). Let me know if you still have any suggestions for us.
