### ISSUE TITLE
 error: unable to recognize "deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1" with lesson-5-kubernetes-for-production/demos/reverse-proxy/deploy/deployment.yaml with Kubernetes version 1.18

### ISSUE THREAD

**Issue by technolytic** [udacity/nd9990-c3-microservices-exercises#27]
With Kubernetes version **1.18**, applying the deployment file:

[https://github.com/udacity/nd9990-c3-microservices-exercises/blob/master/lesson-5-kubernetes-for-production/demos/reverse-proxy/deploy/deployment.yaml](https://github.com/udacity/nd9990-c3-microservices-exercises/blob/master/lesson-5-kubernetes-for-production/demos/reverse-proxy/deploy/deployment.yaml)

causes the following error: 

> error: unable to recognize "deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

The solution is to convert the deployment file as follows:

`kubectl convert -f deployment.yaml --output-version apps/v1`

and copy/paste the result in the deployment file to apply.

**Comment by SudKul** [comment]
Hi @technolytic 
Apologies for an extremely delayed response. We are cleaning up the Udacity repos. 
In such cases ^, I'd request the future learners to use the right platform - https://knowledge.udacity.com/  for discussing individual issues. 
Let me know if you still have any suggestions for us.
